// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FormRequest is an autogenerated mock type for the FormRequest type
type FormRequest struct {
	mock.Mock
}

// Validate provides a mock function with given fields: model, err
func (_m *FormRequest) Validate(model interface{}, err error) map[string]string {
	ret := _m.Called(model, err)

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(interface{}, error) map[string]string); ok {
		r0 = rf(model, err)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}
